[build]
  command = "npm install"
  functions = "netlify/functions"

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/cancel"
  to = "/cancel.html"
  status = 200
